version: '3'

services:
  bot:
    build: .
    container_name: discord_bot
    restart: always
    depends_on:
      - lavalink

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: lavalink
    restart: always
    ports:
      - "2333:2333"
    environment:
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=your_password
      - LAVALINK_SOURCES=youtube,soundcloud,bandsintown,twitch,vimeo
      - LAVALINK_BUFFER_DURATION_MS=400
      - LAVALINK_YOUTUBE_DL_ENABLED=true