version: '3'

services:
  bot:
    build: .
    container_name: discord_bot
    restart: always
    depends_on:
      - lavalink

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:3
    container_name: lavalink
    restart: always
    ports:
      - "2333:2333"
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml
    environment:
      - SERVER_PORT=2333
